name: Deploy to VPS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.VPS_DEPLOY_KEY }}

    - name: Add VPS host to known_hosts
      run: |
        ssh-keyscan -p ${{ secrets.VPS_PORT }} ${{ secrets.VPS_IP }} >> ~/.ssh/known_hosts

    - name: Clean VPS directory
      run: |
        ssh -o StrictHostKeyChecking=no -p ${{ secrets.VPS_PORT }} ${{ secrets.VPS_HOST }} "rm -rf ${{ secrets.VPS_APP_DIR }}/node_modules; find ${{ secrets.VPS_APP_DIR }} -mindepth 1 -exec rm -rf {} +"

    - name: Copy files to VPS
      run: |
        rsync -avz --delete -e "ssh -p ${{ secrets.VPS_PORT }}" ./ ${{ secrets.VPS_HOST }}:${{ secrets.VPS_APP_DIR }}/

    - name: Install npm dependencies
      run: |
        ssh -o StrictHostKeyChecking=no -p ${{ secrets.VPS_PORT }} ${{ secrets.VPS_HOST }} "export PATH=/opt/nvm/versions/node/v22.4.0/bin:$PATH; cd ${{ secrets.VPS_APP_DIR }} && /opt/nvm/versions/node/v22.4.0/bin/npm install"

    - name: Create export web application
      run: |
        ssh -o StrictHostKeyChecking=no -p ${{ secrets.VPS_PORT }} ${{ secrets.VPS_HOST }} "export PATH=/opt/nvm/versions/node/v22.4.0/bin:$PATH; cd ${{ secrets.VPS_APP_DIR }} && /opt/nvm/versions/node/v22.4.0/bin/npm run build"

    - name: Delete all except the dist folder
      run: |
        ssh -o StrictHostKeyChecking=no -p ${{ secrets.VPS_PORT }} ${{ secrets.VPS_HOST }} "rm -rf ${{ secrets.VPS_APP_DIR }}/node_modules; find ${{ secrets.VPS_APP_DIR }} -mindepth 1 -not -name 'dist' -not -path '${{ secrets.VPS_APP_DIR }}/dist/*' -exec rm -rf {} +"

    - name: Create File ENVS
      run: |
        ssh -o StrictHostKeyChecking=no -p ${{ secrets.VPS_PORT }} ${{ secrets.VPS_HOST }} "echo -e '#!/bin/bash\n cd ${{ secrets.VPS_APP_DIR }}\n' > ${{ secrets.VPS_APP_DIR }}/install_dependencies.sh"

    - name: Move all from the dist folder to the current directory
      run: |
        ssh -o StrictHostKeyChecking=no -p ${{ secrets.VPS_PORT }} ${{ secrets.VPS_HOST }} "mv ${{ secrets.VPS_APP_DIR }}/dist/* ${{ secrets.VPS_APP_DIR }}/"

    - name: Remove dist folder
      run: |
        ssh -o StrictHostKeyChecking=no -p ${{ secrets.VPS_PORT }} ${{ secrets.VPS_HOST }} "rm -rf ${{ secrets.VPS_APP_DIR }}/dist"

    - name: Create .htaccess file
      run: |
        ssh -o StrictHostKeyChecking=no -p ${{ secrets.VPS_PORT }} ${{ secrets.VPS_HOST }} "echo -e '<IfModule mod_rewrite.c>\nRewriteEngine On\nRewriteBase /\n# Redireciona tudo para index.html\nRewriteRule ^index\.html$ - [L]\nRewriteCond %{REQUEST_FILENAME} !-f\nRewriteCond %{REQUEST_FILENAME} !-d\nRewriteRule . /index.html [L]\n</IfModule>' > ${{ secrets.VPS_APP_DIR }}/.htaccess"
